import { LANGUAGE_DISPLAY_NAMES } from '@core/domain/config.js';

export const ANALYSIS_PROMPT_VERSION = 3;

export const retrievalBriefing =
  'Write for retrieval: months from now someone will look for this clip with a handful of remembered words, so every line has to carry the details that separate it from a hundred similar ones. Read the text that is visible in the frames - signs, placards, banners, shop and street names, vehicle registrations, printed or on-screen dates, screens, labels, numbers - and use what you can actually read. Prefer exact on-screen or spoken strings when they are legibly readable on screen or clearly and audibly spoken, preserving distinctive specifics such as "jektemodell" instead of replacing them with generic scene language. Apply the same entity evidence rule to every claim in the DESCRIPTION, FILENAME, and TAGS: an entity may appear only when it is legibly readable on screen or clearly and audibly spoken. If an entity fails that test, replace it with a generic descriptor such as "boat exhibit placard" everywhere; it must never survive in the description or tags while being suppressed from the filename. CONCRETE-ATTRIBUTE FLOOR: when no entity passes the evidence test, the filename and tags MUST be composed from directly visible attributes — subject + material/colour + setting/action (e.g. "wooden-boat-exhibit-hall-projection", "museum-sticker-covered-sign-closeup"). Producing "video", any numbered variant of it (e.g. "video-2"), or an empty tag array is a CONTRACT VIOLATION. A minimum of 3 attribute tags is always required. Worked example — no-legible-entity museum clip: FILENAME: wooden-boat-exhibit-hall-projection; TAGS: wooden-boat, exhibit-hall, wall-projection, museum-display. If no speech is present, explicitly state that there is no speech; never invent utterances, languages, or lyrics. Make setting and location claims only when visually supported; never reframe the visible setting as a different place. Describe uncertain audio generically as music or ambience, without language or genre claims unless unambiguous. Never invent names or facts, and never guess at text that is too small or too blurred to read.';

export const descriptionInstruction =
  '2-4 sentences on what the video actually shows: the concrete subject, the place, what happens, and the distinctive text or names you verified from the frames or the audio, quoted as they appear. Open with what makes this clip identifiable instead of the category it belongs to. Do not speculate beyond what you can see or hear.';

export const filenameInstruction =
  'a lowercase kebab-case filename (no dates, no extension) built so a future search lands on this exact clip: most distinctive verifiable detail first - proper names, text you read, place, subject, action. Apply the shared entity evidence rule to the filename. When an entity fails verification, build the filename from verifiable attributes of the clip, such as square-sail-boat-17-knots or wooden-boat-cabin-green-wheel. Three words when that is honestly all the clip offers, up to eight when the content earns them. Never fall back to meaningless names such as video or video-2. Never use filler words such as video, clip, footage, recording, scene or movie, and never settle for a generic label like museum-exhibit or boat-display when anything more specific is visible.';

export const tagsInstruction =
  '3-8 comma-separated kebab-case tags that work as search handles: concrete objects, place type, activity, and notable text or proper nouns that pass the shared entity evidence rule. Tags must always carry the verifiable attributes of the clip, including those used for an attribute-based filename fallback. An empty TAGS value or empty tag array is forbidden. Prefer exact legible or audible strings when they pass the test, and never tag the medium itself (video, clip, footage).';

export const outputLanguageInstruction = (outputLanguage: string): string =>
  outputLanguage === 'auto'
    ? ''
    : `\n\nWrite the DESCRIPTION and the FILENAME in ${LANGUAGE_DISPLAY_NAMES[outputLanguage] ?? outputLanguage}. Keep the TAGS in ASCII kebab-case English regardless of the description language.`;
