export const CHANNELS = {
  appGetVersion: 'app:getVersion',
  apiRequest: 'api:request',
  windowClose: 'window:close',
  windowMinimize: 'window:minimize',
  windowMaximize: 'window:maximize',
  folderShowPicker: 'folder:showPicker',
  folderGetCurrent: 'folder:getCurrent',
  folderSetCurrent: 'folder:setCurrent',
  folderGetRecent: 'folder:getRecent',
  folderRemoveRecent: 'folder:removeRecent',
  folderClearRecent: 'folder:clearRecent',
  folderChanged: 'folder:changed',
  revealInFinder: 'shell:revealInFinder',
  menuOpenFolder: 'menu:openFolder',
  menuOpenRecentFolder: 'menu:openRecentFolder',
  menuClearRecentFolders: 'menu:clearRecentFolders',
  menuToggleTerminal: 'menu:toggleTerminal',
  menuToggleSidebar: 'menu:toggleSidebar',
  menuShowSettings: 'menu:showSettings',
  menuShowPrerequisites: 'menu:showPrerequisites',
  menuShowModelManager: 'menu:showModelManager',
  menuShowSetupWizard: 'menu:showSetupWizard',
  appRelaunch: 'app:relaunch',
  onboardingGetCompleted: 'onboarding:getCompleted',
  onboardingSetCompleted: 'onboarding:setCompleted',
} as const;
